### ISSUE TITLE
Idea: Add Support for Pathfinder Tokens: Bestiaries (Foundry VTT)

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [MostTornBrain/pf2e-md-exporter#1]
You can purchase the Bestiary Images separately from Paizo. 
https://paizo.com/products/btq02eat?Pathfinder-Tokens-Bestiaries

The naming convention is as:
pf2e-tokens-bestiaries\tokens\aberrant\humanoid\Doppleganger.webp
pf2e-tokens-bestiaries\tokens\elemental\fire\Ember-fox.webp.

**Example Names**
![image](https://github.com/MostTornBrain/pf2e-md-exporter/assets/96321415/e9c0f421-98f0-4a80-af80-ab4f3c6f89a0)

**Idea:**
Add an optional handlebar file that can be selected for the bestiary that adds:

---
token: monster-name.webp
---

Users would need to purchase the pack from Paizo and copy the content into their vault. 

**Note:** There are 2 variations of images that come with the pack. Rings and Portraits. The naming convention is the same so the user would need to only copy the folder with the images they want to use as copying both folders would cause a conflict.

**Comment by ObsidianTTRPGProject** [comment]
Here is a copy of the handlebar that will handle the images. 

Adds this:
token: "[[{{ more-handlebars-helpers-replace name (more-handlebars-helpers-regexp ' ') '-' }}.webp]]"

Known Issues: There are monsters this wont work for. The Spell casting dragons for example. There are no individual images for these. This will work with the official Bestiary pack. The battlezoo images use underscore (_) instead of dashes (-) between each word in a monster name. This only works with dashes (-). I would recommend renaming the battlezoo images when they are copied into the vault to use dashes (-) so that a common format is maintained across the vault. 

[monster_handlebar_img.md](https://github.com/MostTornBrain/pf2e-md-exporter/files/14650910/monster_handlebar_img.md)

**Comment by MostTornBrain** [comment]
This is a cool idea.  I'll look into adding an option to export the tokens if you own them.

**Comment by MostTornBrain** [comment]
Do you think it would make sense for the module detect if an custom token image is owned and to export the referenced .webp image as well into a tokens folder as part of the .zip file, or just add the "token" text reference line to the Markdown file and it is assumed the user will manually copy the images to their Vault?

Based on how each monster references the tokens, it appears that it should be possible for the handlebar to detect which monsters have images supplied by a module (such as the bestiary tokens module) vs. those that are using the default system tokens.   For example, I own the Abomination Vaults and the Beginner Box modules, and when I have those imported into a world, any monsters in the Bestiary that have tokens provided by these modules have a custom texture.src value that starts with "module/..." rather than "system/..."   So, the handlebar can check if the texture.src starts with "modules/" and include the token line, otherwise omit it.

**Comment by MostTornBrain** [comment]
Release v0.6.0 now supports an option (off by default) which will detect non-system-default monster images and will export them.  This will require you have the custom images installed in the world where you are doing the export. 

**NOTE:** This will work with an incomplete set of images that are supplied by any module(s).  For example, I own the Beginner's Box and Abomination Vaults modules and if I enable these modules in my world and do an export with this option on, all of my monsters that have custom artwork provided by these modules will that artwork exported.

**Comment by MostTornBrain** [comment]
One further note - this change is entirely optional (which is why I made it of by default).  If you do not want to have this plugin export the images and want to use the approach listed by @ObsidianTTRPGProject you would instead maintain your own copy of all the images in your vault and use the custom monster handlebar he provided earlier in this thread.
