### ISSUE TITLE
Feature request: link to actors from Journal Entries

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#10]
The Journal entries that are created with PDF Importer have at the bottom of the location description a block quote with a link to an actor. When this is exported to markdown, the creature name is exported as plain text. It would be handy if it were exported as a link to an actor.

E.g. this: 
![Screenshot 2024-06-22 at 5 42 48 PM](https://github.com/MostTornBrain/pf2e-md-exporter/assets/1970249/0b4a9bcb-45fa-4a23-b982-c5266500bbb7)
is exported as this:
```
> Charau-ka Butchers (3) - CREATURE 6  
> Page 85  
> **Initiative** Perception +7 (+11 if on alert)
```
I'm requesting that it instead be exported as this:
```
> [[Charau-ka Butcher]]s (3) - CREATURE 6  
> Page 85  
> **Initiative** Perception +7 (+11 if on alert)

```

or, better yet, as an Initiative Tracker encounter:

```
```encounter
creatures:
  - 3 Charau-ka Butcher
\```
```

**Comment by MostTornBrain** [comment]
This is an interesting idea.  I'll see how hard it would be to parse this.  I can see the tagged data in the JSON file - I just have to figure out how these @Actor links are currently getting turned into plain text.  This link conversion functionality is inherited from the original Markdown Exporter, so I am not yet familiar with how that part of the code works. :-)

**Comment by MostTornBrain** [comment]
Turning those entries into links turned out to be easier than I thought it would be.  It'll look something like this:
![image](https://github.com/MostTornBrain/pf2e-md-exporter/assets/15065999/cc433b38-4c9c-4657-9420-4cc3239f4650)
I'll post a new version with this change likely some time tomorrow (6/23) after I do some more testing.    I need to think about the initiative tracker idea for a bit more. If I implement it, it would likely be at a later date when I have some more free time.

**Comment by scooper4711** [comment]
This is perfect. Thank you!

**Comment by MostTornBrain** [comment]
v0.9.5 handles this new feature.   It will create a Markdown link for any referenced actors.
