### ISSUE TITLE
weapon/equipment traits not exported

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#15]
I noticed that weapon traits such as "attached" or "thrown" aren't exported as notes.

E.g. Shield Boss has the trait "attached-to-shield" which is linked to, but never exported when exporting all equipment.

Same goes for e.g. "magical", "thrown" etc.

**Comment by MostTornBrain** [comment]
The item export is far from complete.  It was initially done as a quick placeholder to have the main text of the item's description, but there is a lot of customization still needed for all the different item types.   There are literally 20 or so unique handlebars that could be written for all the different item types.  I've only made specialized item handlebars for spells and weapons and even the weapons one could likely use some more improvement.

**Comment by MostTornBrain** [comment]
Also, for the item's exported, they are meant to use the custom CSS which leverages the "link" format of the traits so they are rendered to look like traits are in the printed books. They aren't really links when the custom CSS is loaded (i.e. you can't click on them), and aren't meant to actually link to another note.

At some point, when I have time, I had intended to redo the item export so they are statblocks which would make the trait rendering more standard and wouldn't use this hackish link syntax for rendering.

**Comment by MostTornBrain** [comment]
Using the "Shield Boss" example, it should look like this if you have the pf2e-spell.css snippet active:
<img width="673" alt="image" src="https://github.com/user-attachments/assets/f28fb7bd-2409-4362-8a16-2ad07ba6e691">
When it is viewed in this manner, the "attached-to-shield" trait is not a clickable link.  When view in source mode, I can see it could cause confusion because it appears as a link.

**Comment by scooper4711** [comment]
Yeah, it totally looks like that. 

The problem I'm trying to solve is easy access to the weapon traits from e.g. Fantasy Statblocks.

I'd like them to act something like this:
<img width="487" alt="Screenshot 2024-07-20 at 7 08 30 PM" src="https://github.com/user-attachments/assets/f7c37e0f-a171-4e30-be46-65124b413113">

The workaround is to have the Weapons Trait page from the GM Screen pinned.

**Comment by MostTornBrain** [comment]
The problem is there is no separate note for each weapon trait.  The text you show in the above screenshot is not present in the PF2E Foundry github data for the open licensed data.  At least, doing a github search I cannot find it.    All the text for the GM screen is in a single file and when it gets parsed, it gets split into separate notes.  But, even then, all the weapon traits are in an HTML table, and looking at the source code for the GM screen file, the weapon traits aren't really even there.  For example, the line for "weapon reach" is simply: "<td style=\"vertical-align:top\"><h4><strong>@Localize[PF2E.TraitReach]</strong></h4></td><td>@Localize[PF2E.TraitDescriptionReach]</td></tr>"   The @Localize call appears to pull in the title and description for whatever native language the Foundry UI is configured.  

There is not an easy way to pull in this data so the trait tags link to it. With a lot of programming it is possibly doable, but it is not something I would have the time do any time soon.   I can make this an enhancement request so it's not forgotten, but I can't guarantee when I might have time to implement it.

**Comment by MostTornBrain** [comment]
Looking into this a bit more, there _might_ be an easy way to create notes for all traits in the system, and then the traits in a statblock would automatically link to them.   I need to think on it a bit more, but maybe I can have some time to get something over the next week.

**Comment by scooper4711** [comment]
That would be great! I really appreciate all the work you’ve done here! Exporting the foundry data to obsidian makes for such a great table-side experience!

**Comment by MostTornBrain** [comment]
I confirmed I can programmatically access all the traits by name and get their descriptions.  Since they aren't part of any specific note, for the export I'm adding a new setting to the module to choose to export all the traits as notes.  This will cause the creation of a set of notes for all traits in the system and then put these notes into a separate folder. This will then allow having traits in the statblock link to them so you can have the hovered description. 

It's a bit of a brute-force approach because when the option is enabled, you'll export a set of traits notes for ALL the traits, not just the traits the exported note might contain.    The note create is very fast, so it won't take a noticeably longer time to export, but even if you just export 1 creature or item, you will also get a folder of all the trait description notes if you enable this feature.

**Comment by MostTornBrain** [comment]
I'm still working on the feature - I ran out of free time today, so hopefully will get to finish it later this coming week.

**Comment by MostTornBrain** [comment]
I think it's just about there:
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/648c22ed-b256-4bd3-858e-c41682ae83a1">

I'll likely push the update later tonight once I do some more testing.

**Comment by MostTornBrain** [comment]
v0.9.12 includes these changes.   You will need to enable the option in the module to export traits.  It is disabled by default.

**Comment by MostTornBrain** [comment]
Hmmm...   somehow I messed up a file when merging in my change from my test setup.  I'll need to uploaded another revision.

**Comment by MostTornBrain** [comment]
v0.9.13 is the proper change.  I had missed updating one file in the previous revision.

**Comment by MostTornBrain** [comment]
v0.9.14 adds trait links within all the handlebars.   NOTE: the `pf2e-spell.css` file must be installed in the Obsidian snippets folder, otherwise the traits won't look right.
