### ISSUE TITLE
With the most recent versions of software I'm seeing a reoccuring error in the exports

### ISSUE THREAD

**Issue by Drunemeton** [MostTornBrain/pf2e-md-exporter#27]
**FVTT:** Version 12, Build 331
**PF2E:** 6.6.2
**PF2E Exporter:** 0.9.24
**libWrapper:** 1.13.2.0
**More Handlebars Helpers:** 1.4.2 (listed as outdated)

Having selected the default settings as shown in the _README.md_ file (with the image option turned on), and having downloaded the _entire compendium_, I'm seeing the following throughout the exported files:

_**Rogue.md**_ _used as an example:_
```
Rogue Resilience Level 9
@Embed[Compendium.pf2e.classfeatures.Item.fMHYzXEUMoWskKMF inline]

Rogue Expertise Level 11
@Embed[Compendium.pf2e.classfeatures.Item.f3Dh32EU4VsHu01b inline]

Greater Rogue Reflexes Level 13
@Embed[Compendium.pf2e.classfeatures.Item.BTpL6XvMk4jvVYYJ inline]
```

I'm unsure what kind of code this is, but it seems to be attempting to make the "[…]" reference (which are all valid references in the exported file set) an inline object. 
I'm unsure if this is attempting to create an active link to those files, or if the exporter process was somehow interrupted in building complete pages. Sort of like how `tp.file.include` will insert text into a note in a non-updatable format.

**Comment by MostTornBrain** [comment]
Thank you for the report.   It looks like something changed in the underlying data organization in a recent Foundry/PF2E update.   Looking at my export done a month or so ago those sections in the example above contain human readable descriptions.

I'll investigate to figure out what might have changed in the data source.

**Comment by MostTornBrain** [comment]
I confirmed it is something with the PF2E 6.6 and higher data that has a change.   I last ran my export with 6.4.1, which worked, but upgrade to the currently latest PF2E data (6.7.0) I am seeing the issue described above.

I'm now looking into how my scripts can work around the change.

**Comment by MostTornBrain** [comment]
Unfortunately, there is not an easy solution to this change in data format.   The embedded document contents cannot be retrieved synchronously.  Best I can do as a short term solution is turn the `@embed` tags into links to the actual document.   That will give something like this:

![image](https://github.com/user-attachments/assets/6d8d40f3-bd24-452a-a409-d764346c5957)

One can then hover over the links to get the full description.   It's not an ideal solution since you can't read the text inline and have to hover over each item to read it.

I'm investigating what might be doable to asynchronously fetch the text, but it will require a fairly extensive rewrite of the module code since all the javascript functions were written to be synchronous.   Plus, if any handlebar ends up referencing these `@embed` tags, they will not be able to resolve them since handlebars must be synchronous and can not use asynchronous functions.   Ug, what a mess.  :-(

**Comment by MostTornBrain** [comment]
In case anyone is curious, this is the error returned if one tries to get the embedded document contents synchronously:

```
Unable to fetch label from Compendium for Compendium.pf2e.journals.JournalEntry.S55aqwWIzpQRFhcq.JournalEntryPage.WZgFEMDSP9TvYc4u:Encounter Budget Error: fromUuidSync was invoked on UUID 'Compendium.pf2e.journals.JournalEntry.S55aqwWIzpQRFhcq.JournalEntryPage.WZgFEMDSP9TvYc4u' which references an Embedded Document and cannot be retrieved synchronously.
```

**Comment by MostTornBrain** [comment]
I think I've figured out a way to deal with the async data mess.  I hope to have a fix pushed in the next day or two, barring no other unexpected issues.

**Comment by MostTornBrain** [comment]
> If it's not too much bother can you confirm that I can fix this on my end with the `tp.file.include` function from Templater?

It will work, but I don't think that would give you the best result as the full statblock version of the docoument rather than just the body of the text.    For example, with the rogue feats, you would get what looks like the stand-alone feature document inserted into the middle of the Rogue class description and it would have a redundant title of the feat.

I should have a fix pushed tomorrow.   I have a proof-of-concept working now.  I just need to clean up the code a bit before checking it in.   This is what the rogue class will look like as an example:

![image](https://github.com/user-attachments/assets/d6842dde-ce13-4039-8551-34875714f74e)

**Comment by MostTornBrain** [comment]
If you've noticed there are other documents besides journal entries that have these @embed tags, please let me know.   If it turns out these are now in bestiary entries, for example, that will still be a problem.  I'm hoping this new format hasn't migrated to there as I don't yet know a way to fix entries that are processed by the handlebars.

**Comment by MostTornBrain** [comment]
Release v0.9.25 fixes this issue.      https://github.com/MostTornBrain/pf2e-md-exporter/tree/v0.9.25
